#!/usr/bin/env python3
"""Backtest Script — MeanRankRevGrowth

Factor ID: 4a483a60aae1c941
Paper: Lakonishok, Josef, Andrei Shleifer, and Robert W. Vishny (1993), NBER Working Paper No. 4360.

Auto-generated by factor-replication-agent.
This is a standalone script: run it with `python3 <filename>.py`

Signal input mode: compustat

This script is a thin wrapper around `BacktestExecutor.run_with_config()` — it
does not re-implement the 9-step backtest lifecycle. Requires this repo to be
installed / importable (e.g. `pip install -e .`).

Requirements:
  - pandas, numpy
  - CRSP monthly data at: /Users/shengzhaolei/Desktop/shengzhao lei/projects/factor-replication-agent/data/crsp_msf.parquet
    Expected columns: permno, yyyymm (or date), ret, me, shrcd, exchcd, siccd
  - Raw WRDS-shaped source tables under: /Users/shengzhaolei/Desktop/shengzhao lei/projects/factor-replication-agent/data
    Sources read: compustat_fundamental_annual
"""

import json
import os
from pathlib import Path

import pandas as pd

from src.infra.models.plugin import PluginRecord
from src.infra.backtest_engine import BacktestExecutor


# ===========================================================================
# CONFIGURATION (derived from resolved MethodSpec)
# ===========================================================================

CONFIG = {
    "breakpoint_source": "full_sample",
    "breakpoint_quantiles": 10,
    "weighting_rule": "vw",
    "rebalance_frequency": "annual",
    "holding_period_months": 12,
    "accounting_lag_months": 6,
    "formation_lag_months": 0,
    "signal_max_staleness_months": 11,
    "signal_cadence": "low_frequency",
    "missing_action": "drop",
    "formation_month": 4,
    "formation_month_explicit": True,
    "sample_start_year": 1968,
    "sample_end_year": 1990,
    "publication_year": 1993,
    "universe_filters": [{'field': 'exchcd', 'op': 'in', 'value': [1, 2]}],
    "unapplied_universe_filters": [],
    "universe_filter_join_sources": {},
    "transforms": [],
    "unapplied_transforms": [{'kind': 'rank', 'stage': 'after_signal', 'bounds': None, 'reason': 'engine has no implementation for this transform kind/stage combination'}],
    "apply_delisting_returns": True,
    "return_combination_type": "extreme_group_spread",
    "return_basis": "excess",
    "estimator": "portfolio_sort",
    "long_leg": "low",
    "short_leg": "high",
    "long_portfolios": [1],
    "short_portfolios": [10],
    "returns_table": "crsp_msf",
    "returns_layout": "crsp_ciz",
    "defaults_applied": [{'config_key': 'accounting_lag_months', 'value': 6, 'reason': 'MethodSpec field unspecified; engine default applied', 'paper_value': None}, {'config_key': 'missing_action', 'value': 'drop', 'reason': 'MethodSpec field unspecified or off-menu; engine default applied', 'paper_value': 'unspecified'}],
}

FACTOR_ID = "4a483a60aae1c941"
# DATA_PATH/SIGNAL_DATA_DIR are runtime-overridable via env vars (falling
# back to the value baked in at generation time) -- this lets the EXACT SAME
# validated script (identical code, identical sha256) run against a
# DIFFERENT data source at execution time (e.g. Step4 validates against a
# small real-data sample, Step5 executes against the full real data/local
# export) without needing to rebuild/re-validate a byte-different script.
# Only the data SOURCE changes this way -- the compute_signal code itself,
# which is what step4's validation actually checks, is untouched.
DATA_PATH = os.environ.get("BACKTEST_DATA_PATH", "/Users/shengzhaolei/Desktop/shengzhao lei/projects/factor-replication-agent/data/crsp_msf.parquet")
# Read from CONFIG (not a separately-baked constant) so a
# config_overrides={"accounting_lag_months": ...} experiment actually takes
# effect here -- this used to be an independently-templated
# `spec.accounting_lag_months or 6` that silently ignored any override to the
# CONFIG key of the same name (see docs/multi-config-evidence-plan.md D4 /
# docs/decision-log.md 2026-08-03).
ACCOUNTING_LAG_MONTHS = CONFIG["accounting_lag_months"]
SIGNAL_INPUT_MODE = "compustat"  # "compustat" | "crsp_only" | "multi_source"
SIGNAL_DATA_DIR = os.environ.get("BACKTEST_SIGNAL_DATA_DIR", "/Users/shengzhaolei/Desktop/shengzhao lei/projects/factor-replication-agent/data")  # multi_source only: dir of raw WRDS-shaped tables
SIGNAL_INPUT_SOURCES = {'compustat_fundamental_annual': ['sale']}  # multi_source only: {source: [columns]}
CRSP_FISCAL_YEAR_END_COLUMNS = []  # match fiscal month through CCM, then apply accounting lag
OUTPUT_PATH = "/Users/shengzhaolei/Desktop/shengzhao lei/projects/factor-replication-agent/runs/backtest_scripts/results/4a483a60aae1c941/factorial_weighting.csv"
FF_FACTORS_PATH = "/Users/shengzhaolei/Desktop/shengzhao lei/projects/factor-replication-agent/data/local/ff_factors.parquet"  # optional; empty string if not supplied
LIQUIDITY_FACTORS_DATA_DIR = "/Users/shengzhaolei/Desktop/shengzhao lei/projects/factor-replication-agent/data"  # optional; dir containing local/liquidity_factors.csv


# ===========================================================================
# SIGNAL PLUGIN (generated by MetaCoder) — compute_signal(). Kept as a source
# string (not spliced as raw code) so the exact same text can be exec'd here
# AND passed to BacktestExecutor as a PluginRecord, keeping the in-process
# engine and this script running identical signal code.
# ===========================================================================

PLUGIN_CODE = 'import pandas as pd\n\ndef compute_signal(df: pd.DataFrame) -> pd.DataFrame:\n    df = df.copy().sort_values(["permno", "time_avail_m"])\n    prior_sales = df.groupby("permno")["sale"].shift(1)\n    df["sales_growth"] = df["sale"] / prior_sales - 1\n    df.loc[prior_sales == 0, "sales_growth"] = float("nan")\n\n    df["growth_rank"] = df.groupby("time_avail_m")["sales_growth"].rank(\n        method="average"\n    )\n\n    rank_lags = [df.groupby("permno")["growth_rank"].shift(i) for i in range(5)]\n    df["signal"] = sum(\n        weight * rank_lag\n        for weight, rank_lag in zip([5, 4, 3, 2, 1], rank_lags)\n    ) / 15\n\n    df = df[df["signal"].notna() & df["signal"].map(lambda x: float("-inf") < x < float("inf"))]\n    return df[["permno", "time_avail_m", "signal"]].rename(\n        columns={"time_avail_m": "yyyymm"}\n    )'

exec(compile(PLUGIN_CODE, "<plugin:4a483a60aae1c941>", "exec"), globals())


def load_msf(path: str) -> pd.DataFrame:
    """Load CRSP monthly stock file: the legacy pre-flattened parquet at
    `path` if it exists (kept for existing synthetic-data/golden-number
    fixtures that still ship one), otherwise assembled from the real WRDS
    "new CIZ" raw-table export directory (SIGNAL_DATA_DIR) the same way
    "multi_source" mode's `main()` branch does. Without this fallback, a
    "compustat"/"crsp_only" mode factor run against a real-data-only snapshot
    (data/local/*.csv, no crsp_msf.parquet) fails here with a misleading
    "Data file not found" even though the real data IS present, just not in
    the legacy pre-flattened format."""
    p = Path(path)
    if not p.exists():
        # SIGNAL_DATA_DIR is the PARENT of the raw-CSV "local" folder (the
        # same convention `assemble_signal_master_table_from_sources()` uses
        # -- it appends "/local" itself); `build_crsp_monthly_panel_ciz()`
        # wants the actual CSV directory, so append it here too.
        from src.infra.data_layer import build_crsp_monthly_panel_ciz
        return build_crsp_monthly_panel_ciz(Path(SIGNAL_DATA_DIR) / "local")
    df = pd.read_parquet(p)
    df.columns = [c.lower() for c in df.columns]
    if "date" in df.columns and "yyyymm" not in df.columns:
        df["yyyymm"] = (
            pd.to_datetime(df["date"]).dt.year * 100
            + pd.to_datetime(df["date"]).dt.month
        )
    for col in ("permno", "yyyymm"):
        if col in df.columns:
            df[col] = df[col].astype(int)
    return df


def build_signal_input(msf: pd.DataFrame) -> pd.DataFrame:
    """Build the DataFrame passed to compute_signal(): a source-driven
    SignalMasterTable [permno, time_avail_m, *cols] via the declarative
    multi-source loader (both "compustat" and "multi_source" modes share one
    loader), or CRSP-only data with yyyymm aliased to time_avail_m
    ("crsp_only", for price-based signals like momentum)."""
    if SIGNAL_INPUT_MODE in ("multi_source", "compustat"):
        from src.infra.data_layer import assemble_signal_master_table_from_sources
        return assemble_signal_master_table_from_sources(
            SIGNAL_DATA_DIR, SIGNAL_INPUT_SOURCES, ACCOUNTING_LAG_MONTHS,
            crsp_fiscal_year_end_columns=CRSP_FISCAL_YEAR_END_COLUMNS,
        )
    return msf.rename(columns={"yyyymm": "time_avail_m"})


def join_universe_filter_sources(msf: pd.DataFrame) -> pd.DataFrame:
    """Point-in-time join any non-CRSP-native columns a `universe_filters`
    entry needs (CONFIG["universe_filter_join_sources"]: {source: [columns]},
    see `registry._universe_filter_join_sources`) onto the returns panel
    BEFORE the engine runs -- so `filter_universe`/`apply_universe_filters`
    see these columns as ordinary panel columns, exactly like `exchcd`/
    `shrcd`, and BacktestExecutor itself needs zero changes. No-op (returns
    `msf` unchanged) when no universe filter needs a non-native column.

    Uses `asof_align_to_monthly` (NOT a plain exact-month merge) -- a
    Compustat-sourced column here is annual-cadence (one row per fiscal
    period), so an exact (permno, yyyymm) merge would only match ~1 of every
    12 months, leaving the rest NaN and silently excluded by a `gt`/`nonzero`
    -style filter even though the firm's value is legitimately still
    available (fixed 2026-08-16 -- see that function's docstring)."""
    join_sources = CONFIG.get("universe_filter_join_sources") or {}
    if not join_sources:
        return msf
    from src.infra.data_layer import assemble_signal_master_table_from_sources, asof_align_to_monthly
    extra = assemble_signal_master_table_from_sources(SIGNAL_DATA_DIR, join_sources, ACCOUNTING_LAG_MONTHS)
    aligned = asof_align_to_monthly(
        msf[["permno", "yyyymm"]], extra, CONFIG.get("signal_max_staleness_months", 11)
    )
    return msf.merge(aligned, on=["permno", "yyyymm"], how="left")



def load_factors() -> pd.DataFrame | None:
    """Load FF factor + rf data (FF_FACTORS_PATH) and/or Pastor-Stambaugh
    liquidity factor data (LIQUIDITY_FACTORS_DATA_DIR), merged into ONE
    `factors` frame on `yyyymm` -- fetched/exported ahead of time via
    scripts/fetch_ff_factors.py / a real WRDS liquidity_factors.csv export,
    never fetched here. Returns None if neither was supplied/found."""
    factors = None
    if FF_FACTORS_PATH:
        p = Path(FF_FACTORS_PATH)
        if p.exists():
            factors = pd.read_parquet(p)
    if LIQUIDITY_FACTORS_DATA_DIR and (Path(LIQUIDITY_FACTORS_DATA_DIR) / "local" / "liquidity_factors.csv").exists():
        from src.infra.data_layer import load_liquidity_factors
        liq = load_liquidity_factors(LIQUIDITY_FACTORS_DATA_DIR)
        factors = liq if factors is None else factors.merge(liq, on="yyyymm", how="outer")
    return factors


def main():
    print(f"=== Backtest: {FACTOR_ID} ===")
    print(f"Signal input mode: {SIGNAL_INPUT_MODE}")
    print()

    if SIGNAL_INPUT_MODE == "multi_source":
        # Returns panel + signal inputs both come from the real WRDS "new
        # CIZ" export under SIGNAL_DATA_DIR/local/ (CRSP_STOCK_MONTH.csv +
        # CRSP_DELISTING.csv assembled into the flat panel; other sources
        # joined by the master-table builder). SIGNAL_DATA_DIR itself is the
        # PARENT of the raw-CSV "local" folder -- the SAME convention
        # `assemble_signal_master_table_from_sources()` uses below (it
        # appends "/local" internally for every raw-CSV source, including
        # CRSP-as-signal-source); `build_crsp_monthly_panel_ciz()` itself
        # wants the actual CSV directory, so it must be appended here too.
        # The legacy 3-table crsp_msf/msenames/msedelist assembler was
        # removed 2026-07-31.
        from src.infra.data_layer import build_crsp_monthly_panel_ciz
        msf = build_crsp_monthly_panel_ciz(Path(SIGNAL_DATA_DIR) / "local")
    else:
        msf = load_msf(DATA_PATH)

    # Point-in-time join any non-CRSP-native universe-filter columns (e.g. a
    # Compustat-only screen like total_assets) onto the returns panel BEFORE
    # the engine runs -- see join_universe_filter_sources() above. No-op
    # when no universe filter needs a non-native column.
    msf = join_universe_filter_sources(msf)

    signal_input = build_signal_input(msf)
    print("Computing signal...")
    signal = compute_signal(signal_input)
    print(f"  Signal: {len(signal):,} observations, {signal['permno'].nunique():,} unique firms")
    print(f"  Date range: {signal['yyyymm'].min()} - {signal['yyyymm'].max()}")

    # Persist the REALIZED signal series (docs/multi-config-evidence-plan.md
    # Phase A1.1). Captured HERE -- compute_signal's own output, before any
    # universe filter / breakpoint / portfolio step -- so a "controlled"
    # post-signal config comparison (e.g. weighting_rule only) can assert
    # this file is unchanged across tracks, and a "controlled" pre-signal
    # comparison (e.g. accounting_lag_months) can confirm it DID change.
    signal_path = Path(OUTPUT_PATH).with_name(Path(OUTPUT_PATH).stem + ".signal.parquet")
    signal_path.parent.mkdir(parents=True, exist_ok=True)
    signal[["permno", "yyyymm", "signal"]].to_parquet(signal_path, index=False)
    print(f"  Signal series saved to: {signal_path}")

    plugin = PluginRecord(plugin_id=f"{FACTOR_ID}_script", factor_id=FACTOR_ID, code=PLUGIN_CODE)
    factors = load_factors()

    print("Running BacktestExecutor...")
    engine = BacktestExecutor()
    result = engine.run_with_config(signal, CONFIG, plugin=plugin, data=msf, factors=factors)
    metrics = result["metrics"]
    ls_returns = result["return_series"]

    print()
    print("=" * 50)
    print("RESULTS")
    print("=" * 50)
    print(f"  Mean monthly return:  {metrics.get('mean_monthly_return', float('nan'))*100:.3f}%")
    print(f"  Annualized return:    {metrics.get('annualized_return', 0)*100:.2f}%")
    print(f"  t-stat (Newey-West):  {metrics.get('t_stat', float('nan')):.2f}")
    print(f"  Sharpe ratio:         {metrics.get('sharpe_ratio', float('nan')):.2f}")
    if "alpha_capm" in metrics:
        print(f"  Alpha (CAPM):         {metrics['alpha_capm']*100:.3f}% (t={metrics['alpha_capm_tstat']:.2f})")
    if "alpha_ff3" in metrics:
        print(f"  Alpha (FF3):          {metrics['alpha_ff3']*100:.3f}% (t={metrics['alpha_ff3_tstat']:.2f})")
    if "alpha_ff5" in metrics:
        print(f"  Alpha (FF5):          {metrics['alpha_ff5']*100:.3f}% (t={metrics['alpha_ff5_tstat']:.2f})")
    print(f"  N months:             {metrics.get('n_months')}")
    print("=" * 50)

    output_path = Path(OUTPUT_PATH)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    ls_returns.to_csv(output_path, index=False)
    print(f"\nReturn series saved to: {output_path}")

    metrics_path = output_path.with_suffix(".metrics.json")
    with open(metrics_path, "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"Metrics saved to: {metrics_path}")


if __name__ == "__main__":
    main()
