"""Tests for the Semantic Extractor module.

Redesigned to use:
1. Real LLM calls (codex CLI) — no mocks
2. Real PDFs from data/papers/ as input
3. SignalDoc.csv as ground truth for evaluation
4. Structured evaluation output (JSON report + per-field breakdown)

Run with:
    pytest tests/test_extractor.py -v --tb=short
    pytest tests/test_extractor.py -k "eval" --tb=short  # evaluation only
"""

import csv
import json
import re
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Optional

import pytest

try:
    import fitz  # PyMuPDF
except ImportError:
    fitz = None

from src.llm import create_llm_client
from src.extractor import (
    ExtractionMetrics,
    ExtractionResult,
    SemanticExtractor,
)
from src.models.method_spec import (
    BreakpointSource,
    EvidenceSource,
    MissingAction,
    MethodSpec,
    RebalanceFrequency,
    WeightingRule,
)


# --- Paths ---

PAPERS_DIR = Path(__file__).parent.parent / "data" / "papers"
SIGNALDOC_PATH = Path(__file__).parent.parent / "data" / "osap" / "SignalDoc.csv"
EVAL_OUTPUT_DIR = Path(__file__).parent.parent / "data" / "eval_output"


# --- PDF → Factor mapping ---
# Maps PDF filename → list of SignalDoc factor Acronyms extractable from that paper.
# Generated by matching SignalDoc Authors+Year to PDF filenames in data/papers/
PDF_FACTOR_MAP: dict[str, list[str]] = {
    "Amihud_2002.pdf": ["Illiquidity"],
    "Baker_1996.pdf": ["RoE", "VarCF", "VolMkt", "VolumeTrend", "CapTurnover"],
    "Bazdresch_2014.pdf": ["hire"],
    "Belo_2014.pdf": ["BrandInvest", "BrandCapital"],
    "Chan_1996.pdf": ["AnnouncementReturn", "REV6"],
    "Chen_2002.pdf": ["DelBreadth"],
    "Cohen_2013.pdf": ["RDAbility"],
    "Datar_1998.pdf": ["ShareVol"],
    "Dechow_2004.pdf": ["EquityDuration"],
    "French_1992.pdf": ["AM", "BMdec", "BookLeverage"],
    "Gou_2006.pdf": ["RDIPO"],
    "Hirschleifer_2013.pdf": ["CitationsRD", "PatentsRD"],
    "Ikenberry_1995.pdf": ["ShareRepurchase"],
    "Kacperczyk_2009.pdf": ["sinAlgo", "sinOrig"],
    "Lakonishok_1994.pdf": ["CF", "MeanRankRevGrowth", "sgr"],
    "Nagel_2005.pdf": ["RIO_Disp", "RIO_MB", "RIO_Turnover", "RIO_Volatility"],
    "Nissim_2004.pdf": ["Tax"],
    "Novy-Marx_2011.pdf": ["OPLeverage"],
    "Novy-Marx_2012.pdf": ["IntMom"],
    "Ozbas_2010.pdf": ["iomom_cust", "iomom_supp"],
    "Palazzo_2012.pdf": ["Cash"],
    "Pedersen_2005.pdf": ["betaCC", "betaCR", "betaNet", "betaRC", "betaRR"],
    "Porta_1996.pdf": ["fgr5yrLag", "fgr5yrNoLag"],
    "Ritter_2005.pdf": ["IO_ShortInterest"],
    "Sinha_2013.pdf": ["DelDRC"],
    "Soliman_2008.pdf": ["ChAssetTurnover", "ChNNCOA", "ChNWC", "AssetTurnover", "ChNCOA", "ChNCOL", "ChPM", "PM", "RetNOA"],
    "Stattman_1980.pdf": ["BM"],
    "Titman_2004.pdf": ["Investment"],
    "Warachka_2011.pdf": ["EarningsForecastDisparity"],
    "Zhang_2002.pdf": ["ChInv"],
    "Zhang_2010.pdf": ["skew1", "invest"],
    "Zhang_2011.pdf": ["ChTax"],
    "al._2007.pdf": ["NetPayoutYield", "PayoutYield"],
}

# Reverse lookup: factor_id → pdf_filename (for convenience)
FACTOR_TO_PDF: dict[str, str] = {
    factor: pdf
    for pdf, factors in PDF_FACTOR_MAP.items()
    for factor in factors
}


# --- Helpers ---


def _extract_pdf_text(pdf_path: Path, max_pages: int = 30) -> str:
    """Extract text from a PDF using PyMuPDF."""
    if fitz is None:
        pytest.skip("PyMuPDF (fitz) not installed")
    doc = fitz.open(str(pdf_path))
    text_parts = []
    for i, page in enumerate(doc):
        if i >= max_pages:
            break
        text_parts.append(page.get_text())
    doc.close()
    return "\n".join(text_parts)


def _load_signaldoc() -> dict[str, dict]:
    """Load SignalDoc.csv into {Acronym: row_dict}."""
    rows = {}
    with open(SIGNALDOC_PATH, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows[row["Acronym"]] = row
    return rows


# Common Compustat/CRSP variable names to extract from Detailed Definition
_KNOWN_VARIABLES = {
    "at", "ceq", "csho", "prcc_f", "ib", "oancf", "act", "che", "lct", "dlc",
    "dp", "txp", "sale", "revt", "cogs", "xsga", "ni", "ebitda", "ppegt",
    "ppent", "invt", "rect", "lt", "dltt", "pstk", "mib", "seq", "txditc",
    "pstkrv", "pstkl", "re", "bkvlps", "dvc", "dvp", "prc", "ret", "vol",
    "shrout", "me", "mktrf", "rf", "fopt", "xrd", "capx", "ivao", "dlt",
}


def _extract_formula_keywords(detailed_def: str) -> list[str]:
    """Extract Compustat/CRSP variable names from SignalDoc Detailed Definition.

    Looks for known variable names in parentheses like "(at)" or "(ceq)"
    and also bare variable names that appear as standalone tokens.
    """
    if not detailed_def:
        return []
    text_lower = detailed_def.lower()
    found = []

    # Match variables in parentheses: (at), (ceq), etc.
    paren_matches = re.findall(r"\(([a-z_]+)\)", text_lower)
    for m in paren_matches:
        if m in _KNOWN_VARIABLES:
            found.append(m)

    # Also check for standalone known variables as tokens
    tokens = set(re.findall(r"\b([a-z_]+)\b", text_lower))
    for var in _KNOWN_VARIABLES:
        if var in tokens and var not in found:
            found.append(var)

    return sorted(set(found))


def _parse_signaldoc_ground_truth(row: dict) -> dict:
    """Convert a SignalDoc.csv row into ground truth dict for evaluation.

    Maps SignalDoc columns to MethodSpec field names.
    Evaluates up to 14 fields per factor.
    """
    gt = {}

    # Weighting
    if row.get("Stock Weight"):
        gt["stock_weight"] = row["Stock Weight"].lower().strip()

    # Formation month
    formation_month = None
    if row.get("Start Month"):
        try:
            formation_month = int(float(row["Start Month"]))
            gt["formation_month"] = str(formation_month)
        except (ValueError, TypeError):
            pass

    # Holding period
    holding_period = None
    if row.get("Portfolio Period"):
        try:
            holding_period = int(float(row["Portfolio Period"]))
            gt["holding_period"] = str(holding_period)
        except (ValueError, TypeError):
            pass

    # Sign and long/short direction
    if row.get("Sign"):
        try:
            sign = int(float(row["Sign"]))
            gt["sign"] = str(sign)
            gt["long_leg"] = "high" if sign == 1 else "low"
            gt["short_leg"] = "low" if sign == 1 else "high"
        except (ValueError, TypeError):
            pass

    # LS Quantile
    if row.get("LS Quantile"):
        try:
            gt["ls_quantile"] = str(float(row["LS Quantile"]))
        except (ValueError, TypeError):
            pass

    # Filter
    if row.get("Filter"):
        gt["filter"] = row["Filter"].strip()

    # Cat.Form
    if row.get("Cat.Form"):
        gt["cat_form"] = row["Cat.Form"].strip().lower()

    # --- New fields ---

    # Formula keywords (from Detailed Definition)
    detailed_def = row.get("Detailed Definition", "")
    keywords = _extract_formula_keywords(detailed_def)
    if keywords:
        gt["formula_keywords"] = ",".join(keywords)

    # Sample start/end year
    if row.get("SampleStartYear"):
        try:
            gt["sample_start_year"] = str(int(float(row["SampleStartYear"])))
        except (ValueError, TypeError):
            pass

    if row.get("SampleEndYear"):
        try:
            gt["sample_end_year"] = str(int(float(row["SampleEndYear"])))
        except (ValueError, TypeError):
            pass

    # Rebalance frequency (derived from holding period)
    if holding_period is not None:
        if holding_period == 1:
            gt["rebalance_frequency"] = "monthly"
        elif holding_period == 12:
            gt["rebalance_frequency"] = "annual"
        elif holding_period == 3:
            gt["rebalance_frequency"] = "quarterly"

    # Accounting lag (derived: if formation_month=6, standard lag=6)
    if formation_month == 6:
        gt["accounting_lag"] = "6"

    return gt


PASS_THRESHOLD = 80  # Score >= 80 means pass


def _compute_score(metrics: Optional[ExtractionMetrics]) -> float:
    """Compute a 0-100 score from ExtractionMetrics. Uses field_accuracy."""
    if metrics is None:
        return 0.0
    return round(metrics.field_accuracy * 100, 1)


@dataclass
class FactorEvalResult:
    """Evaluation result for a single factor."""

    factor_id: str
    pdf_file: str
    metrics: Optional[ExtractionMetrics] = None
    field_details: dict = None  # {field: {"expected": x, "actual": y, "match": bool}}
    extraction_success: bool = False
    error: Optional[str] = None
    score: float = 0.0
    passed: bool = False

    def __post_init__(self):
        if self.field_details is None:
            self.field_details = {}
        if self.metrics and self.score == 0.0:
            self.score = _compute_score(self.metrics)
            self.passed = self.score >= PASS_THRESHOLD


@dataclass
class EvalReport:
    """Aggregate evaluation report across all factors."""

    total_factors: int = 0
    successful_extractions: int = 0
    avg_field_accuracy: float = 0.0
    avg_core_accuracy: float = 0.0
    avg_field_coverage: float = 0.0
    passed_count: int = 0
    failed_count: int = 0
    pass_rate: float = 0.0
    avg_score: float = 0.0
    per_factor: list = None

    def __post_init__(self):
        if self.per_factor is None:
            self.per_factor = []

    def compute_aggregates(self):
        """Recompute aggregate stats from per_factor results."""
        if not self.per_factor:
            return
        self.passed_count = sum(1 for r in self.per_factor if r.passed)
        self.failed_count = self.total_factors - self.passed_count
        self.pass_rate = self.passed_count / self.total_factors if self.total_factors else 0.0
        scores = [r.score for r in self.per_factor if r.extraction_success]
        self.avg_score = sum(scores) / len(scores) if scores else 0.0

    def summary(self) -> str:
        lines = [
            "=" * 60,
            "EXTRACTION EVALUATION REPORT",
            "=" * 60,
            f"Total factors tested:     {self.total_factors}",
            f"Successful extractions:   {self.successful_extractions}",
            f"Passed (>={PASS_THRESHOLD}):          {self.passed_count}",
            f"Failed (<{PASS_THRESHOLD}):            {self.failed_count}",
            f"Pass rate:                {self.pass_rate:.1%}",
            f"Avg score:                {self.avg_score:.1f}/100",
            f"Avg field accuracy:       {self.avg_field_accuracy:.1%}",
            f"Avg core field accuracy:  {self.avg_core_accuracy:.1%}",
            f"Avg field coverage:       {self.avg_field_coverage:.1%}",
            "-" * 60,
        ]
        for r in self.per_factor:
            status = "PASS" if r.passed else "FAIL"
            acc = f"{r.score:.0f}/100" if r.extraction_success else "N/A"
            lines.append(f"  [{status}] {r.factor_id:<20} score={acc}  pdf={r.pdf_file}")
            if r.field_details:
                for field_name, detail in r.field_details.items():
                    mark = "v" if detail["match"] else "x"
                    lines.append(
                        f"        {mark} {field_name}: expected={detail['expected']}, got={detail['actual']}"
                    )
        lines.append("=" * 60)
        return "\n".join(lines)

    def to_json(self) -> dict:
        return {
            "total_factors": self.total_factors,
            "successful_extractions": self.successful_extractions,
            "passed_count": self.passed_count,
            "failed_count": self.failed_count,
            "pass_rate": self.pass_rate,
            "avg_score": self.avg_score,
            "avg_field_accuracy": self.avg_field_accuracy,
            "avg_core_accuracy": self.avg_core_accuracy,
            "avg_field_coverage": self.avg_field_coverage,
            "per_factor": [
                {
                    "factor_id": r.factor_id,
                    "pdf_file": r.pdf_file,
                    "extraction_success": r.extraction_success,
                    "score": r.score,
                    "passed": r.passed,
                    "error": r.error,
                    "metrics": asdict(r.metrics) if r.metrics else None,
                    "field_details": r.field_details,
                }
                for r in self.per_factor
            ],
        }


def _build_field_details(
    extractor: SemanticExtractor, spec: MethodSpec, ground_truth: dict
) -> dict:
    """Build per-field comparison detail dict."""
    details = {}
    for key, expected in ground_truth.items():
        # If ground truth is unspecified/None, treat as correct
        if expected is None or str(expected).strip().lower() in ("", "none", "unspecified", "n/a", "nan"):
            details[key] = {
                "expected": expected,
                "actual": "N/A (ground truth unspecified)",
                "match": True,
            }
            continue

        actual = extractor._get_spec_field(spec, key)
        match = extractor._values_match(actual, expected, field_key=key) if actual is not None else False
        details[key] = {
            "expected": expected,
            "actual": str(actual) if actual is not None else None,
            "match": match,
        }
    return details


# --- Fixtures ---

HAS_CODEX = shutil.which("codex") is not None
HAS_PYMUPDF = fitz is not None
HAS_SIGNALDOC = SIGNALDOC_PATH.exists()


def _available_factors() -> list[str]:
    """Return factor IDs that have both a PDF and a SignalDoc entry."""
    if not HAS_SIGNALDOC or not PAPERS_DIR.exists():
        return []
    signaldoc = _load_signaldoc()
    available = []
    for pdf_name, factors in PDF_FACTOR_MAP.items():
        pdf_path = PAPERS_DIR / pdf_name
        if not pdf_path.exists():
            continue
        for factor_id in factors:
            if factor_id in signaldoc:
                available.append(factor_id)
    return available


AVAILABLE_FACTORS = _available_factors()

# Select pilot factors (subset for faster CI runs)
PILOT_FACTORS = [f for f in ["BM", "Illiquidity", "CF", "Investment", "OPLeverage"] if f in AVAILABLE_FACTORS]


# --- Tests: Real LLM + Real PDF + Ground Truth ---


@pytest.mark.skipif(not HAS_CODEX, reason="codex CLI not installed")
@pytest.mark.skipif(not HAS_PYMUPDF, reason="PyMuPDF not installed")
@pytest.mark.skipif(not HAS_SIGNALDOC, reason="SignalDoc.csv not available")
class TestRealExtraction:
    """End-to-end extraction tests: real PDF -> real LLM -> SignalDoc ground truth."""

    def setup_method(self):
        self.llm_client = create_llm_client(provider="codex")
        self.extractor = SemanticExtractor(llm_client=self.llm_client)
        self.signaldoc = _load_signaldoc()

    @pytest.mark.parametrize("factor_id", PILOT_FACTORS)
    def test_extraction_succeeds(self, factor_id: str):
        """Real LLM should successfully extract from real PDF without crashing."""
        pdf_path = PAPERS_DIR / FACTOR_TO_PDF[factor_id]
        paper_text = _extract_pdf_text(pdf_path)

        result = self.extractor.extract(factor_id, paper_text)

        assert result.spec is not None, f"Extraction returned None spec for {factor_id}"
        assert result.spec.factor_id == factor_id
        assert result.spec.signal.formula is not None
        assert len(result.spec.signal.formula) > 3
        assert result.raw_llm_output is not None

    @pytest.mark.parametrize("factor_id", PILOT_FACTORS)
    def test_extraction_accuracy(self, factor_id: str):
        """Extraction should achieve reasonable accuracy against SignalDoc ground truth."""
        pdf_path = PAPERS_DIR / FACTOR_TO_PDF[factor_id]
        paper_text = _extract_pdf_text(pdf_path)

        result = self.extractor.extract(factor_id, paper_text)
        assert result.spec is not None

        gt = _parse_signaldoc_ground_truth(self.signaldoc[factor_id])
        metrics = self.extractor.evaluate_extraction(result.spec, gt)

        # Phase 1 acceptance: core field accuracy >= 50% (realistic for paper-only)
        assert metrics.field_coverage > 0.0, f"{factor_id}: no fields extracted"
        # Log metrics for visibility
        print(f"\n  {factor_id}: accuracy={metrics.field_accuracy:.0%}, "
              f"core={metrics.core_field_accuracy:.0%}, "
              f"coverage={metrics.field_coverage:.0%}")

    def test_no_llm_client_raises(self):
        """SemanticExtractor without client should raise RuntimeError."""
        extractor = SemanticExtractor(llm_client=None)
        with pytest.raises(RuntimeError, match="LLM client required"):
            extractor.extract("BM", "paper text")


# --- Tests: Full Evaluation Suite ---


@pytest.mark.skipif(not HAS_CODEX, reason="codex CLI not installed")
@pytest.mark.skipif(not HAS_PYMUPDF, reason="PyMuPDF not installed")
@pytest.mark.skipif(not HAS_SIGNALDOC, reason="SignalDoc.csv not available")
class TestFullEvaluation:
    """Run full evaluation across all available factors and produce a report."""

    def setup_method(self):
        self.llm_client = create_llm_client(provider="codex")
        self.extractor = SemanticExtractor(llm_client=self.llm_client)
        self.signaldoc = _load_signaldoc()

    @pytest.mark.slow
    def test_full_eval_report(self):
        """Run extraction on all available PDFs and produce evaluation report.

        Iterates by PDF file to avoid re-reading the same PDF multiple times.
        """
        report = EvalReport()
        report.total_factors = len(AVAILABLE_FACTORS)

        accuracies = []
        core_accuracies = []
        coverages = []

        # Group by PDF to extract text once per file
        for pdf_name, factor_ids in PDF_FACTOR_MAP.items():
            pdf_path = PAPERS_DIR / pdf_name
            if not pdf_path.exists():
                continue

            try:
                paper_text = _extract_pdf_text(pdf_path)
            except Exception as e:
                # Mark all factors from this PDF as failed
                for factor_id in factor_ids:
                    if factor_id in AVAILABLE_FACTORS:
                        eval_result = FactorEvalResult(
                            factor_id=factor_id, pdf_file=pdf_name, error=f"PDF read error: {e}"
                        )
                        report.per_factor.append(eval_result)
                continue

            for factor_id in factor_ids:
                if factor_id not in AVAILABLE_FACTORS:
                    continue
                eval_result = FactorEvalResult(factor_id=factor_id, pdf_file=pdf_name)

                try:
                    result = self.extractor.extract(factor_id, paper_text)

                    if result.spec is None:
                        eval_result.error = "Extraction returned None spec"
                        report.per_factor.append(eval_result)
                        continue

                    eval_result.extraction_success = True
                    report.successful_extractions += 1

                    gt = _parse_signaldoc_ground_truth(self.signaldoc[factor_id])
                    metrics = self.extractor.evaluate_extraction(result.spec, gt)
                    eval_result.metrics = metrics
                    eval_result.field_details = _build_field_details(
                        self.extractor, result.spec, gt
                    )

                    accuracies.append(metrics.field_accuracy)
                    core_accuracies.append(metrics.core_field_accuracy)
                    coverages.append(metrics.field_coverage)

                except Exception as e:
                    eval_result.error = str(e)

                report.per_factor.append(eval_result)

        # Compute averages
        if accuracies:
            report.avg_field_accuracy = sum(accuracies) / len(accuracies)
            report.avg_core_accuracy = sum(core_accuracies) / len(core_accuracies)
            report.avg_field_coverage = sum(coverages) / len(coverages)

        # Write report
        EVAL_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        report_path = EVAL_OUTPUT_DIR / "extraction_eval_report.json"
        with open(report_path, "w") as f:
            json.dump(report.to_json(), f, indent=2)

        summary_path = EVAL_OUTPUT_DIR / "extraction_eval_summary.txt"
        with open(summary_path, "w") as f:
            f.write(report.summary())

        # Print summary
        print(f"\n{report.summary()}")
        print(f"\nReport saved to: {report_path}")

        # At least some extractions should succeed
        assert report.successful_extractions > 0, "No extractions succeeded"

    @pytest.mark.slow
    @pytest.mark.parametrize("factor_id", AVAILABLE_FACTORS)
    def test_individual_factor_eval(self, factor_id: str):
        """Individual factor extraction + evaluation (for granular CI)."""
        pdf_path = PAPERS_DIR / FACTOR_TO_PDF[factor_id]
        paper_text = _extract_pdf_text(pdf_path)

        result = self.extractor.extract(factor_id, paper_text)
        assert result.spec is not None, f"{factor_id}: extraction failed"

        gt = _parse_signaldoc_ground_truth(self.signaldoc[factor_id])
        metrics = self.extractor.evaluate_extraction(result.spec, gt)
        details = _build_field_details(self.extractor, result.spec, gt)

        print(f"\n--- {factor_id} ({FACTOR_TO_PDF[factor_id]}) ---")
        print(f"  Accuracy: {metrics.field_accuracy:.0%} | Core: {metrics.core_field_accuracy:.0%}")
        for field_name, detail in details.items():
            mark = "v" if detail["match"] else "x"
            print(f"  {mark} {field_name}: expected={detail['expected']}, got={detail['actual']}")


# --- Tests: Evaluation Logic (unit tests, no LLM needed) ---


class TestEvaluationLogic:
    """Test evaluation helpers without LLM calls."""

    def setup_method(self):
        from unittest.mock import MagicMock

        self.extractor = SemanticExtractor(llm_client=MagicMock())

    def test_signaldoc_loads(self):
        """SignalDoc.csv should have 200+ factors."""
        if not HAS_SIGNALDOC:
            pytest.skip("SignalDoc.csv not available")
        rows = _load_signaldoc()
        assert len(rows) >= 200

    def test_ground_truth_parsing(self):
        """Ground truth parser should extract known fields correctly."""
        if not HAS_SIGNALDOC:
            pytest.skip("SignalDoc.csv not available")
        rows = _load_signaldoc()

        # BM should be EW, formation=6, holding=12
        if "BM" in rows:
            gt = _parse_signaldoc_ground_truth(rows["BM"])
            assert gt.get("stock_weight") == "ew"
            assert gt.get("formation_month") == "6"

    def test_all_factors_parseable(self):
        """Every SignalDoc row should parse without errors."""
        if not HAS_SIGNALDOC:
            pytest.skip("SignalDoc.csv not available")
        rows = _load_signaldoc()
        parsed_count = 0
        for acronym, row in rows.items():
            gt = _parse_signaldoc_ground_truth(row)
            assert isinstance(gt, dict)
            if gt:
                parsed_count += 1
        assert parsed_count >= 200

    def test_available_factor_pdf_mapping(self):
        """All mapped PDFs should have well-formed filenames."""
        for pdf_name, factors in PDF_FACTOR_MAP.items():
            assert pdf_name.endswith(".pdf") or pdf_name.endswith(".url")
            assert len(factors) > 0

    def test_eval_report_serialization(self):
        """EvalReport should serialize to JSON correctly."""
        report = EvalReport(total_factors=5, successful_extractions=3)
        report.avg_field_accuracy = 0.75
        report.avg_core_accuracy = 0.80
        report.avg_field_coverage = 0.90

        json_data = report.to_json()
        assert json_data["total_factors"] == 5
        assert json_data["avg_field_accuracy"] == 0.75

    def test_eval_report_summary_formatting(self):
        """EvalReport summary should produce readable text."""
        report = EvalReport(total_factors=2, successful_extractions=2)
        report.avg_field_accuracy = 0.80
        report.avg_core_accuracy = 0.75
        report.avg_field_coverage = 1.0
        report.per_factor = [
            FactorEvalResult(
                factor_id="BM",
                pdf_file="French_1992.pdf",
                extraction_success=True,
                metrics=ExtractionMetrics(
                    field_accuracy=0.8, core_field_accuracy=0.75,
                    field_coverage=1.0, ambiguity_rate=0.2
                ),
            )
        ]
        summary = report.summary()
        assert "BM" in summary
        assert "80%" in summary


# --- Standalone eval runner (can be called outside pytest) ---


def run_evaluation(
    factors: list[str] | None = None,
    output_dir: Path | None = None,
) -> EvalReport:
    """Run extraction evaluation programmatically.

    Args:
        factors: List of factor IDs to evaluate. None = all available.
        output_dir: Where to write the report. None = default eval_output dir.

    Returns:
        EvalReport with all results.
    """
    if not HAS_CODEX:
        raise RuntimeError("codex CLI not installed")
    if not HAS_PYMUPDF:
        raise RuntimeError("PyMuPDF not installed -- pip install pymupdf")

    llm_client = create_llm_client(provider="codex")
    extractor = SemanticExtractor(llm_client=llm_client)
    signaldoc = _load_signaldoc()

    factors_to_eval = factors or AVAILABLE_FACTORS
    output_dir = output_dir or EVAL_OUTPUT_DIR

    report = EvalReport(total_factors=len(factors_to_eval))
    accuracies, core_accuracies, coverages = [], [], []

    for factor_id in factors_to_eval:
        if factor_id not in FACTOR_TO_PDF:
            continue
        pdf_path = PAPERS_DIR / FACTOR_TO_PDF[factor_id]
        eval_result = FactorEvalResult(factor_id=factor_id, pdf_file=FACTOR_TO_PDF[factor_id])

        try:
            paper_text = _extract_pdf_text(pdf_path)
            result = extractor.extract(factor_id, paper_text)

            if result.spec is None:
                eval_result.error = "Extraction returned None spec"
                report.per_factor.append(eval_result)
                continue

            eval_result.extraction_success = True
            report.successful_extractions += 1

            gt = _parse_signaldoc_ground_truth(signaldoc[factor_id])
            metrics = extractor.evaluate_extraction(result.spec, gt)
            eval_result.metrics = metrics
            eval_result.score = _compute_score(metrics)
            eval_result.passed = eval_result.score >= PASS_THRESHOLD
            eval_result.field_details = _build_field_details(extractor, result.spec, gt)

            accuracies.append(metrics.field_accuracy)
            core_accuracies.append(metrics.core_field_accuracy)
            coverages.append(metrics.field_coverage)

        except Exception as e:
            eval_result.error = str(e)

        report.per_factor.append(eval_result)

    if accuracies:
        report.avg_field_accuracy = sum(accuracies) / len(accuracies)
        report.avg_core_accuracy = sum(core_accuracies) / len(core_accuracies)
        report.avg_field_coverage = sum(coverages) / len(coverages)

    report.compute_aggregates()

    # Write outputs
    output_dir.mkdir(parents=True, exist_ok=True)
    with open(output_dir / "extraction_eval_report.json", "w") as f:
        json.dump(report.to_json(), f, indent=2)
    with open(output_dir / "extraction_eval_summary.txt", "w") as f:
        f.write(report.summary())

    return report


if __name__ == "__main__":
    """Run evaluation directly: python tests/test_extractor.py"""
    report = run_evaluation()
    print(report.summary())
